services:
  - name: client-ease
    type: web
    env: python
    plan: free
    region: eu-central-1
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 3 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: client-ease-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: SECURITY_PASSWORD_SALT
        sync: false
      - key: EMAIL_VERIFICATION_SALT
        sync: false
