services:
  - type: web
    name: client-ease
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn client_ease:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SECURITY_PASSWORD_SALT
        generateValue: true
      - key: EMAIL_VERIFICATION_SALT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: client-ease-db
          property: connectionString
      - key: BREVO_API_KEY
        sync: false  # You'll set this manually

databases:
  - name: client-ease-db
    plan: free
