"""Add Client Model

Revision ID: 3443f70f575e
Revises: 2d7b9dd99490
Create Date: 2025-02-23 23:03:04.370544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3443f70f575e'
down_revision = '2d7b9dd99490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_name'))
        batch_op.drop_index(batch_op.f('ix_client_email'))

    op.drop_table('client')
    # ### end Alembic commands ###
