"""Add invoice model

Revision ID: 7264fd64fdec
Revises: d5e2c1dd103e
Create Date: 2025-03-22 13:24:49.744759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7264fd64fdec'
down_revision = 'd5e2c1dd103e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.create_index(batch_op.f('ix_invoice_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('total_amount')
        batch_op.drop_column('due_date')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('issue_date')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('issue_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.FLOAT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_invoice_user_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_project_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_client_id'))
        batch_op.drop_column('amount')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
